### ISSUE TITLE
cannot create requesttojoin proposal on rinkeby..

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/common-scripts#3]
I'm _not_ managing to create a request to join proposal on rinkeby with the script here:
https://github.com/daostack/common-scripts/blob/master/createRequestToJoin.js#L35

This is an example of a failing transaction: https://rinkeby.etherscan.io/tx/0x31c878d11cff018f29a79c3f70b30480d40e352e9d930043c65822c3d62187ac

The fundingrequest scheme looks fine on https://api.thegraph.com/subgraphs/name/daostack/v7_4_exp_rinkeby

(in particular, the parameters seem to be set correctly (which was an earlier problem))

```
{ controllerSchemes (where: { address: "0xe4482d6dc3740b815b20da8c7c81d52fef73e1d7"}) {
  id 
  name
  dao { name }
  fundingRequestParams { id }
joinAndQuitParams { id 
  minFeeToJoin
}
}}
```
results in 
```
{
  "data": {
    "controllerSchemes": [
      {
        "dao": {
          "name": "Test DAO 76972"
        },
        "fundingRequestParams": null,
        "id": "0x052e827059eb63585577b9fa4b804ff6118e5a4cd3c04925ff074d6b9604521f",
        "joinAndQuitParams": {
          "id": "0xe4482d6dc3740b815b20da8c7c81d52fef73e1d7",
          "minFeeToJoin": "100"
        },
        "name": "JoinAndQuit"
      }
    ]
  }
}
```

**Comment by ben-kaufman** [comment]
Hi @jellegerbrandy,
The issue is happening because the proposer is already a member of the common (the creator). The JoinAndQuit scheme does not allow an existing member to propose himself again and thus the script fails. You need to send the transaction from another account, which is not a member of the common and it should work then.
